/* eslint-disable semi */
/* eslint-disable max-len */
/* eslint-disable comma-dangle */
/* eslint-disable quote-props */
module.exports = {
  'admin': false,
  'answers': {
    'across': [
      'PERTURBS',
      'LADED',
      'EXNIHILO',
      'FELIPE',
      'TEAMUPON',
      'TAPSIN',
      'RECORDDEALS',
      'HYDRA',
      'KGB',
      'PEE',
      'EURO',
      'BRIT',
      'APPS',
      'AGOG',
      'TUA',
      'HONEST',
      'POPULISM',
      'AMWAY',
      'MEANT',
      'TSAR',
      'ESPTESTS',
      'RIG',
      'SPAT',
      'ROEG',
      'SNOG',
      'ALLAH',
      'SLR',
      'AGER',
      'GUITARSOLO',
      'DATE',
      'AMNESIA',
      'STACHE',
      'SEESPOT',
      'SETTER'
    ],
    'down': [
      'PET',
      'EXE',
      'RNA',
      'TIM',
      'UHURA',
      'RIPE',
      'BLOCKBUSTER',
      'SONOGRAM',
      'LEAD',
      'ALPE',
      'DISAPPEARINGACT',
      'EPILEPSY',
      'DENSEST',
      'FTD',
      'RBI',
      'HEAP',
      'YUGO',
      'DROPMEALINE',
      'ROGUESTATES',
      'THATSGROSS',
      'ANWARSADAT',
      'TINT',
      'OMS',
      'LAP',
      'SOSO',
      'TELL',
      'GOETHE',
      'SAGAS',
      'PLUME',
      'GREER',
      'HASP',
      'RIO',
      'SAT',
      'TETRIS'
    ]
  },
  'author': 'Brandon Koppy',
  'auto': false,
  'clueDictionary': {
    'across': [
      null,
      {
        'answer': 'PERTURBS',
        'clue': '1. Troubles',
        'index': 0,
        'isLastClue': false,
        'nextGridNum': 9,
        'prevGridNum': -1
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      {
        'answer': 'LADED',
        'clue': '9. Got on board, in a way',
        'index': 10,
        'isLastClue': false,
        'nextGridNum': 14,
        'prevGridNum': 1
      },
      null,
      null,
      null,
      null,
      {
        'answer': 'EXNIHILO',
        'clue': '14. Out of nothing, in creation myths',
        'index': 15,
        'isLastClue': false,
        'nextGridNum': 15,
        'prevGridNum': 9
      },
      {
        'answer': 'FELIPE',
        'clue': '15. Spanish monarch beginning in 2014',
        'index': 24,
        'isLastClue': false,
        'nextGridNum': 16,
        'prevGridNum': 14
      },
      {
        'answer': 'TEAMUPON',
        'clue': '16. Tackle together',
        'index': 30,
        'isLastClue': false,
        'nextGridNum': 17,
        'prevGridNum': 15
      },
      {
        'answer': 'TAPSIN',
        'clue': '17. Sinks from not far away',
        'index': 39,
        'isLastClue': false,
        'nextGridNum': 18,
        'prevGridNum': 16
      },
      {
        'answer': 'RECORDDEALS',
        'clue': '18. Dreams for aspiring bands',
        'index': 49,
        'isLastClue': false,
        'nextGridNum': 20,
        'prevGridNum': 17
      },
      null,
      {
        'answer': 'HYDRA',
        'clue': '20. Many-headed monster',
        'index': 60,
        'isLastClue': false,
        'nextGridNum': 24,
        'prevGridNum': 18
      },
      null,
      null,
      null,
      {
        'answer': 'KGB',
        'clue': '24. Org. that &quot;Moscow Centre&quot; represents in George Smiley novels',
        'index': 66,
        'isLastClue': false,
        'nextGridNum': 25,
        'prevGridNum': 20
      },
      {
        'answer': 'PEE',
        'clue': '25. &quot;___-yew!&quot;',
        'index': 72,
        'isLastClue': false,
        'nextGridNum': 26,
        'prevGridNum': 24
      },
      {
        'answer': 'EURO',
        'clue': '26. Prefix with zone or pop',
        'index': 75,
        'isLastClue': false,
        'nextGridNum': 27,
        'prevGridNum': 25
      },
      {
        'answer': 'BRIT',
        'clue': '27. George Smiley, for one',
        'index': 81,
        'isLastClue': false,
        'nextGridNum': 29,
        'prevGridNum': 26
      },
      null,
      {
        'answer': 'APPS',
        'clue': '29. Mozz sticks and queso, e.g.',
        'index': 86,
        'isLastClue': false,
        'nextGridNum': 30,
        'prevGridNum': 27
      },
      {
        'answer': 'AGOG',
        'clue': '30. Utterly amazed',
        'index': 90,
        'isLastClue': false,
        'nextGridNum': 31,
        'prevGridNum': 29
      },
      {
        'answer': 'TUA',
        'clue': '31. N.F.L. QB Tagovailoa',
        'index': 95,
        'isLastClue': false,
        'nextGridNum': 32,
        'prevGridNum': 30
      },
      {
        'answer': 'HONEST',
        'clue': '32. Upright',
        'index': 99,
        'isLastClue': false,
        'nextGridNum': 34,
        'prevGridNum': 31
      },
      null,
      {
        'answer': 'POPULISM',
        'clue': '34. Anti-establishment cause',
        'index': 105,
        'isLastClue': false,
        'nextGridNum': 36,
        'prevGridNum': 32
      },
      null,
      {
        'answer': 'AMWAY',
        'clue': '36. Big name in multilevel marketing',
        'index': 114,
        'isLastClue': false,
        'nextGridNum': 37,
        'prevGridNum': 34
      },
      {
        'answer': 'MEANT',
        'clue': '37. Had in mind',
        'index': 122,
        'isLastClue': false,
        'nextGridNum': 38,
        'prevGridNum': 36
      },
      {
        'answer': 'TSAR',
        'clue': '38. Fyodor the Blessed, e.g.',
        'index': 129,
        'isLastClue': false,
        'nextGridNum': 39,
        'prevGridNum': 37
      },
      {
        'answer': 'ESPTESTS',
        'clue': '39. Experiments with Zener cards',
        'index': 137,
        'isLastClue': false,
        'nextGridNum': 42,
        'prevGridNum': 38
      },
      null,
      null,
      {
        'answer': 'RIG',
        'clue': '42. Computer custom-built for playing games, in slang',
        'index': 146,
        'isLastClue': false,
        'nextGridNum': 44,
        'prevGridNum': 39
      },
      null,
      {
        'answer': 'SPAT',
        'clue': '44. Conflict of no consequence',
        'index': 150,
        'isLastClue': false,
        'nextGridNum': 46,
        'prevGridNum': 42
      },
      null,
      {
        'answer': 'ROEG',
        'clue': '46. Nicolas who directed &quot;Don&#39;t Look Now&quot;',
        'index': 156,
        'isLastClue': false,
        'nextGridNum': 47,
        'prevGridNum': 44
      },
      {
        'answer': 'SNOG',
        'clue': '47. French, perhaps, in England',
        'index': 161,
        'isLastClue': false,
        'nextGridNum': 49,
        'prevGridNum': 46
      },
      null,
      {
        'answer': 'ALLAH',
        'clue': '49. One also known as Rahman',
        'index': 165,
        'isLastClue': false,
        'nextGridNum': 51,
        'prevGridNum': 47
      },
      null,
      {
        'answer': 'SLR',
        'clue': '51. Mirror-and-prism system, in brief',
        'index': 172,
        'isLastClue': false,
        'nextGridNum': 52,
        'prevGridNum': 49
      },
      {
        'answer': 'AGER',
        'clue': '52. Golden ___',
        'index': 176,
        'isLastClue': false,
        'nextGridNum': 53,
        'prevGridNum': 51
      },
      {
        'answer': 'GUITARSOLO',
        'clue': '53. It can be shredded with an ax',
        'index': 180,
        'isLastClue': false,
        'nextGridNum': 56,
        'prevGridNum': 52
      },
      null,
      null,
      {
        'answer': 'DATE',
        'clue': '56. One of three things traditionally eaten to break a Ramadan fast',
        'index': 191,
        'isLastClue': false,
        'nextGridNum': 57,
        'prevGridNum': 53
      },
      {
        'answer': 'AMNESIA',
        'clue': '57. Ironic-sounding plot device in &quot;Total Recall&quot;',
        'index': 195,
        'isLastClue': false,
        'nextGridNum': 58,
        'prevGridNum': 56
      },
      {
        'answer': 'STACHE',
        'clue': '58. It&#39;s just under one&#39;s nose, informally',
        'index': 204,
        'isLastClue': false,
        'nextGridNum': 60,
        'prevGridNum': 57
      },
      null,
      {
        'answer': 'SEESPOT',
        'clue': '60. Iconic phrase in old &quot;Dick and Jane&quot; stories',
        'index': 210,
        'isLastClue': false,
        'nextGridNum': 61,
        'prevGridNum': 58
      },
      {
        'answer': 'SETTER',
        'clue': '61. Irish ___',
        'index': 219,
        'isLastClue': true,
        'nextGridNum': -1,
        'prevGridNum': 60
      }
    ],
    'down': [
      null,
      {
        'answer': 'PET',
        'clue': '1. Snit',
        'index': 0,
        'isLastClue': false,
        'nextGridNum': 2,
        'prevGridNum': -1
      },
      {
        'answer': 'EXE',
        'clue': '2. Suffix for many install files',
        'index': 1,
        'isLastClue': false,
        'nextGridNum': 3,
        'prevGridNum': 1
      },
      {
        'answer': 'RNA',
        'clue': '3. Modern vaccine material',
        'index': 2,
        'isLastClue': false,
        'nextGridNum': 4,
        'prevGridNum': 2
      },
      {
        'answer': 'TIM',
        'clue': '4. &quot;___ and Eric Awesome Show, Great Job!&quot; (comedy sketch series)',
        'index': 3,
        'isLastClue': false,
        'nextGridNum': 5,
        'prevGridNum': 3
      },
      {
        'answer': 'UHURA',
        'clue': '5. Classic role for Nichelle Nichols and Zoë Saldana',
        'index': 4,
        'isLastClue': false,
        'nextGridNum': 6,
        'prevGridNum': 4
      },
      {
        'answer': 'RIPE',
        'clue': '6. Quite stinky',
        'index': 5,
        'isLastClue': false,
        'nextGridNum': 7,
        'prevGridNum': 5
      },
      {
        'answer': 'BLOCKBUSTER',
        'clue': '7. Hugely successful film … or an apt description of a 59-Down player?',
        'index': 6,
        'isLastClue': false,
        'nextGridNum': 8,
        'prevGridNum': 6
      },
      {
        'answer': 'SONOGRAM',
        'clue': '8. Picture of health?',
        'index': 7,
        'isLastClue': false,
        'nextGridNum': 9,
        'prevGridNum': 7
      },
      {
        'answer': 'LEAD',
        'clue': '9. Direct',
        'index': 10,
        'isLastClue': false,
        'nextGridNum': 10,
        'prevGridNum': 8
      },
      {
        'answer': 'ALPE',
        'clue': '10. Mont Blanc, par exemple',
        'index': 11,
        'isLastClue': false,
        'nextGridNum': 11,
        'prevGridNum': 9
      },
      {
        'answer': 'DISAPPEARINGACT',
        'clue': '11. Trick of being suddenly nowhere to be found … or an apt description of victory for a 59-Down player?',
        'index': 12,
        'isLastClue': false,
        'nextGridNum': 12,
        'prevGridNum': 10
      },
      {
        'answer': 'EPILEPSY',
        'clue': '12. The &quot;sacred disease,&quot; to ancient Greeks',
        'index': 13,
        'isLastClue': false,
        'nextGridNum': 13,
        'prevGridNum': 11
      },
      {
        'answer': 'DENSEST',
        'clue': '13. Like osmium among all the elements',
        'index': 14,
        'isLastClue': false,
        'nextGridNum': 15,
        'prevGridNum': 12
      },
      null,
      {
        'answer': 'FTD',
        'clue': '15. Busy business around Mother&#39;s Day',
        'index': 24,
        'isLastClue': false,
        'nextGridNum': 19,
        'prevGridNum': 13
      },
      null,
      null,
      null,
      {
        'answer': 'RBI',
        'clue': '19. 1 of 2,297 for Hank Aaron',
        'index': 53,
        'isLastClue': false,
        'nextGridNum': 20,
        'prevGridNum': 15
      },
      {
        'answer': 'HEAP',
        'clue': '20. Load',
        'index': 60,
        'isLastClue': false,
        'nextGridNum': 21,
        'prevGridNum': 19
      },
      {
        'answer': 'YUGO',
        'clue': '21. Bygone car named for its country of origin',
        'index': 61,
        'isLastClue': false,
        'nextGridNum': 22,
        'prevGridNum': 20
      },
      {
        'answer': 'DROPMEALINE',
        'clue': '22. &quot;Don&#39;t be a stranger&quot; … or an apt request from a 59-Down player?',
        'index': 62,
        'isLastClue': false,
        'nextGridNum': 23,
        'prevGridNum': 21
      },
      {
        'answer': 'ROGUESTATES',
        'clue': '23. Bad lands?',
        'index': 63,
        'isLastClue': false,
        'nextGridNum': 28,
        'prevGridNum': 22
      },
      null,
      null,
      null,
      null,
      {
        'answer': 'THATSGROSS',
        'clue': '28. &quot;Eww!&quot;',
        'index': 84,
        'isLastClue': false,
        'nextGridNum': 29,
        'prevGridNum': 23
      },
      {
        'answer': 'ANWARSADAT',
        'clue': '29. One of two 1978 Nobel Peace Price winners',
        'index': 86,
        'isLastClue': false,
        'nextGridNum': 31,
        'prevGridNum': 28
      },
      null,
      {
        'answer': 'TINT',
        'clue': '31. Coloring',
        'index': 95,
        'isLastClue': false,
        'nextGridNum': 33,
        'prevGridNum': 29
      },
      null,
      {
        'answer': 'OMS',
        'clue': '33. Sacred syllables',
        'index': 100,
        'isLastClue': false,
        'nextGridNum': 35,
        'prevGridNum': 31
      },
      null,
      {
        'answer': 'LAP',
        'clue': '35. Unit in Mario Kart games',
        'index': 109,
        'isLastClue': false,
        'nextGridNum': 40,
        'prevGridNum': 33
      },
      null,
      null,
      null,
      null,
      {
        'answer': 'SOSO',
        'clue': '40. Meh',
        'index': 142,
        'isLastClue': false,
        'nextGridNum': 41,
        'prevGridNum': 35
      },
      {
        'answer': 'TELL',
        'clue': '41. Poker table giveaway',
        'index': 143,
        'isLastClue': false,
        'nextGridNum': 43,
        'prevGridNum': 40
      },
      null,
      {
        'answer': 'GOETHE',
        'clue': '43. &quot;Faust&quot; playwright',
        'index': 148,
        'isLastClue': false,
        'nextGridNum': 44,
        'prevGridNum': 41
      },
      {
        'answer': 'SAGAS',
        'clue': '44. Stories that might take a while',
        'index': 150,
        'isLastClue': false,
        'nextGridNum': 45,
        'prevGridNum': 43
      },
      {
        'answer': 'PLUME',
        'clue': '45. Distinctive peacock feature',
        'index': 151,
        'isLastClue': false,
        'nextGridNum': 48,
        'prevGridNum': 44
      },
      null,
      null,
      {
        'answer': 'GREER',
        'clue': '48. Actress Judy of &quot;Arrested Development&quot;',
        'index': 164,
        'isLastClue': false,
        'nextGridNum': 50,
        'prevGridNum': 45
      },
      null,
      {
        'answer': 'HASP',
        'clue': '50. Trunk fastener',
        'index': 169,
        'isLastClue': false,
        'nextGridNum': 54,
        'prevGridNum': 48
      },
      null,
      null,
      null,
      {
        'answer': 'RIO',
        'clue': '54. ___ Grande',
        'index': 185,
        'isLastClue': false,
        'nextGridNum': 55,
        'prevGridNum': 50
      },
      {
        'answer': 'SAT',
        'clue': '55. Took a load off',
        'index': 186,
        'isLastClue': false,
        'nextGridNum': 59,
        'prevGridNum': 54
      },
      null,
      null,
      null,
      {
        'answer': 'TETRIS',
        'clue': '59. Best-selling video game celebrated in this grid',
        'index': 205,
        'isLastClue': true,
        'nextGridNum': -1,
        'prevGridNum': 55
      }
    ]
  },
  'clues': {
    'across': [
      '1. Troubles',
      '9. Got on board, in a way',
      '14. Out of nothing, in creation myths',
      '15. Spanish monarch beginning in 2014',
      '16. Tackle together',
      '17. Sinks from not far away',
      '18. Dreams for aspiring bands',
      '20. Many-headed monster',
      '24. Org. that &quot;Moscow Centre&quot; represents in George Smiley novels',
      '25. &quot;___-yew!&quot;',
      '26. Prefix with zone or pop',
      '27. George Smiley, for one',
      '29. Mozz sticks and queso, e.g.',
      '30. Utterly amazed',
      '31. N.F.L. QB Tagovailoa',
      '32. Upright',
      '34. Anti-establishment cause',
      '36. Big name in multilevel marketing',
      '37. Had in mind',
      '38. Fyodor the Blessed, e.g.',
      '39. Experiments with Zener cards',
      '42. Computer custom-built for playing games, in slang',
      '44. Conflict of no consequence',
      '46. Nicolas who directed &quot;Don&#39;t Look Now&quot;',
      '47. French, perhaps, in England',
      '49. One also known as Rahman',
      '51. Mirror-and-prism system, in brief',
      '52. Golden ___',
      '53. It can be shredded with an ax',
      '56. One of three things traditionally eaten to break a Ramadan fast',
      '57. Ironic-sounding plot device in &quot;Total Recall&quot;',
      '58. It&#39;s just under one&#39;s nose, informally',
      '60. Iconic phrase in old &quot;Dick and Jane&quot; stories',
      '61. Irish ___'
    ],
    'down': [
      '1. Snit',
      '2. Suffix for many install files',
      '3. Modern vaccine material',
      '4. &quot;___ and Eric Awesome Show, Great Job!&quot; (comedy sketch series)',
      '5. Classic role for Nichelle Nichols and Zoë Saldana',
      '6. Quite stinky',
      '7. Hugely successful film … or an apt description of a 59-Down player?',
      '8. Picture of health?',
      '9. Direct',
      '10. Mont Blanc, par exemple',
      '11. Trick of being suddenly nowhere to be found … or an apt description of victory for a 59-Down player?',
      '12. The &quot;sacred disease,&quot; to ancient Greeks',
      '13. Like osmium among all the elements',
      '15. Busy business around Mother&#39;s Day',
      '19. 1 of 2,297 for Hank Aaron',
      '20. Load',
      '21. Bygone car named for its country of origin',
      '22. &quot;Don&#39;t be a stranger&quot; … or an apt request from a 59-Down player?',
      '23. Bad lands?',
      '28. &quot;Eww!&quot;',
      '29. One of two 1978 Nobel Peace Price winners',
      '31. Coloring',
      '33. Sacred syllables',
      '35. Unit in Mario Kart games',
      '40. Meh',
      '41. Poker table giveaway',
      '43. &quot;Faust&quot; playwright',
      '44. Stories that might take a while',
      '45. Distinctive peacock feature',
      '48. Actress Judy of &quot;Arrested Development&quot;',
      '50. Trunk fastener',
      '54. ___ Grande',
      '55. Took a load off',
      '59. Best-selling video game celebrated in this grid'
    ]
  },
  'copyright': '2022, The New York Times',
  'date': '9/9/2022',
  'dow': 'Friday',
  'editor': 'Will Shortz',
  'gameGrid': [
    {
      'acrossStart': true,
      'answer': 'P',
      'circle': false,
      'downStart': true,
      'gridNum': 1,
      'id': 0,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': true,
      'gridNum': 2,
      'id': 1,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': true,
      'gridNum': 3,
      'id': 2,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': true,
      'gridNum': 4,
      'id': 3,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'U',
      'circle': false,
      'downStart': true,
      'gridNum': 5,
      'id': 4,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': true,
      'gridNum': 6,
      'id': 5,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'B',
      'circle': false,
      'downStart': true,
      'gridNum': 7,
      'id': 6,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': true,
      'gridNum': 8,
      'id': 7,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 8,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 9,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'L',
      'circle': false,
      'downStart': true,
      'gridNum': 9,
      'id': 10,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': true,
      'gridNum': 10,
      'id': 11,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'D',
      'circle': false,
      'downStart': true,
      'gridNum': 11,
      'id': 12,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': true,
      'gridNum': 12,
      'id': 13,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'D',
      'circle': false,
      'downStart': true,
      'gridNum': 13,
      'id': 14,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 14,
      'id': 15,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'X',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 16,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'N',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 17,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 18,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'H',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 19,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 20,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 21,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 22,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 23,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'F',
      'circle': false,
      'downStart': true,
      'gridNum': 15,
      'id': 24,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 25,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 26,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 27,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 28,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 29,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 16,
      'id': 30,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 31,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 32,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'M',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 33,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'U',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 34,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 35,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 36,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'N',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 37,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 38,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 17,
      'id': 39,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 40,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 41,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 42,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 43,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'N',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 44,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 45,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 46,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 47,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 48,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 18,
      'id': 49,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 50,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'C',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 51,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 52,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': true,
      'gridNum': 19,
      'id': 53,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'D',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 54,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'D',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 55,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 56,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 57,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 58,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 59,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'H',
      'circle': false,
      'downStart': true,
      'gridNum': 20,
      'id': 60,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'Y',
      'circle': false,
      'downStart': true,
      'gridNum': 21,
      'id': 61,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'D',
      'circle': false,
      'downStart': true,
      'gridNum': 22,
      'id': 62,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': true,
      'gridNum': 23,
      'id': 63,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 64,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 65,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'K',
      'circle': false,
      'downStart': false,
      'gridNum': 24,
      'id': 66,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'G',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 67,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'B',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 68,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 69,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 70,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 71,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 25,
      'id': 72,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 73,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 74,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 26,
      'id': 75,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'U',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 76,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 77,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 78,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 79,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 80,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'B',
      'circle': false,
      'downStart': false,
      'gridNum': 27,
      'id': 81,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 82,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 83,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': true,
      'gridNum': 28,
      'id': 84,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 85,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'A',
      'circle': false,
      'downStart': true,
      'gridNum': 29,
      'id': 86,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 87,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 88,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 89,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 30,
      'id': 90,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'G',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 91,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 92,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'G',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 93,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 94,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'T',
      'circle': false,
      'downStart': true,
      'gridNum': 31,
      'id': 95,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'U',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 96,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 97,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 98,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'H',
      'circle': false,
      'downStart': false,
      'gridNum': 32,
      'id': 99,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': true,
      'gridNum': 33,
      'id': 100,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'N',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 101,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 102,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 103,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 104,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 34,
      'id': 105,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 106,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 107,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'U',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 108,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': true,
      'gridNum': 35,
      'id': 109,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 110,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 111,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'M',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 112,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 113,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 36,
      'id': 114,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'M',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 115,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'W',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 116,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 117,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'Y',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 118,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 119,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 120,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 121,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'M',
      'circle': false,
      'downStart': false,
      'gridNum': 37,
      'id': 122,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 123,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 124,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'N',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 125,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 126,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 127,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 128,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 38,
      'id': 129,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 130,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 131,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 132,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 133,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 134,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 135,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 136,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 39,
      'id': 137,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 138,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 139,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 140,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 141,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': true,
      'gridNum': 40,
      'id': 142,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': true,
      'gridNum': 41,
      'id': 143,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 144,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 145,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 42,
      'id': 146,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 147,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'G',
      'circle': false,
      'downStart': true,
      'gridNum': 43,
      'id': 148,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 149,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'S',
      'circle': false,
      'downStart': true,
      'gridNum': 44,
      'id': 150,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': true,
      'gridNum': 45,
      'id': 151,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 152,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 153,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 154,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 155,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 46,
      'id': 156,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 157,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 158,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'G',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 159,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 160,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 47,
      'id': 161,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'N',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 162,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 163,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'G',
      'circle': false,
      'downStart': true,
      'gridNum': 48,
      'id': 164,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 49,
      'id': 165,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 166,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 167,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 168,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'H',
      'circle': false,
      'downStart': true,
      'gridNum': 50,
      'id': 169,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 170,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 171,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 51,
      'id': 172,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 173,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 174,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 175,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 52,
      'id': 176,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'G',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 177,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 178,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 179,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'G',
      'circle': false,
      'downStart': false,
      'gridNum': 53,
      'id': 180,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'U',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 181,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 182,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 183,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 184,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': true,
      'gridNum': 54,
      'id': 185,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': true,
      'gridNum': 55,
      'id': 186,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 187,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'L',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 188,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 189,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 190,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'D',
      'circle': false,
      'downStart': false,
      'gridNum': 56,
      'id': 191,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 192,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 193,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 194,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 57,
      'id': 195,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'M',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 196,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'N',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 197,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 198,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 199,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 200,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 201,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 202,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 203,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 58,
      'id': 204,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': true,
      'gridNum': 59,
      'id': 205,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'A',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 206,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'C',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 207,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'H',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 208,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 209,
      'isPlayable': true
    },
    {
      'acrossStart': true,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 60,
      'id': 210,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 211,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 212,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 213,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'P',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 214,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'O',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 215,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 216,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 217,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 218,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 61,
      'id': 219,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 220,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 221,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 222,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'E',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 223,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 224,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 225,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 226,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 227,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 228,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 229,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 230,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 231,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 232,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 233,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 234,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'T',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 235,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 236,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 237,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 238,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 239,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 240,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 241,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 242,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 243,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 244,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 245,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 246,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 247,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 248,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 249,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'R',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 250,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 251,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 252,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 253,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 254,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 255,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 256,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 257,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 258,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 259,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 260,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 261,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 262,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 263,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 264,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'I',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 265,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 266,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 267,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 268,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 269,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 270,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 271,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 272,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 273,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 274,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 275,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 276,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 277,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 278,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 279,
      'isPlayable': false
    },
    {
      'acrossStart': true,
      'answer': 'S',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 280,
      'isPlayable': true
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 281,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 282,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 283,
      'isPlayable': false
    },
    {
      'acrossStart': false,
      'answer': '.',
      'circle': false,
      'downStart': false,
      'gridNum': 0,
      'id': 284,
      'isPlayable': false
    }
  ],
  'grid': [
    'P',
    'E',
    'R',
    'T',
    'U',
    'R',
    'B',
    'S',
    '.',
    '.',
    'L',
    'A',
    'D',
    'E',
    'D',
    'E',
    'X',
    'N',
    'I',
    'H',
    'I',
    'L',
    'O',
    '.',
    'F',
    'E',
    'L',
    'I',
    'P',
    'E',
    'T',
    'E',
    'A',
    'M',
    'U',
    'P',
    'O',
    'N',
    '.',
    'T',
    'A',
    'P',
    'S',
    'I',
    'N',
    '.',
    '.',
    '.',
    '.',
    'R',
    'E',
    'C',
    'O',
    'R',
    'D',
    'D',
    'E',
    'A',
    'L',
    'S',
    'H',
    'Y',
    'D',
    'R',
    'A',
    '.',
    'K',
    'G',
    'B',
    '.',
    '.',
    '.',
    'P',
    'E',
    'E',
    'E',
    'U',
    'R',
    'O',
    '.',
    '.',
    'B',
    'R',
    'I',
    'T',
    '.',
    'A',
    'P',
    'P',
    'S',
    'A',
    'G',
    'O',
    'G',
    '.',
    'T',
    'U',
    'A',
    '.',
    'H',
    'O',
    'N',
    'E',
    'S',
    'T',
    'P',
    'O',
    'P',
    'U',
    'L',
    'I',
    'S',
    'M',
    '.',
    'A',
    'M',
    'W',
    'A',
    'Y',
    '.',
    '.',
    '.',
    'M',
    'E',
    'A',
    'N',
    'T',
    '.',
    '.',
    'T',
    'S',
    'A',
    'R',
    '.',
    '.',
    '.',
    '.',
    'E',
    'S',
    'P',
    'T',
    'E',
    'S',
    'T',
    'S',
    '.',
    'R',
    'I',
    'G',
    '.',
    'S',
    'P',
    'A',
    'T',
    '.',
    '.',
    'R',
    'O',
    'E',
    'G',
    '.',
    'S',
    'N',
    'O',
    'G',
    'A',
    'L',
    'L',
    'A',
    'H',
    '.',
    '.',
    'S',
    'L',
    'R',
    '.',
    'A',
    'G',
    'E',
    'R',
    'G',
    'U',
    'I',
    'T',
    'A',
    'R',
    'S',
    'O',
    'L',
    'O',
    '.',
    'D',
    'A',
    'T',
    'E',
    'A',
    'M',
    'N',
    'E',
    'S',
    'I',
    'A',
    '.',
    '.',
    'S',
    'T',
    'A',
    'C',
    'H',
    'E',
    'S',
    'E',
    'E',
    'S',
    'P',
    'O',
    'T',
    '.',
    '.',
    'S',
    'E',
    'T',
    'T',
    'E',
    'R',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    'T',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    'R',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    'I',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    '.',
    'S',
    '.',
    '.',
    '.',
    '.'
  ],
  'gridnums': [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    0,
    0,
    9,
    10,
    11,
    12,
    13,
    14,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    15,
    0,
    0,
    0,
    0,
    0,
    16,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    17,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    18,
    0,
    0,
    0,
    19,
    0,
    0,
    0,
    0,
    0,
    0,
    20,
    21,
    22,
    23,
    0,
    0,
    24,
    0,
    0,
    0,
    0,
    0,
    25,
    0,
    0,
    26,
    0,
    0,
    0,
    0,
    0,
    27,
    0,
    0,
    28,
    0,
    29,
    0,
    0,
    0,
    30,
    0,
    0,
    0,
    0,
    31,
    0,
    0,
    0,
    32,
    33,
    0,
    0,
    0,
    0,
    34,
    0,
    0,
    0,
    35,
    0,
    0,
    0,
    0,
    36,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    37,
    0,
    0,
    0,
    0,
    0,
    0,
    38,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    39,
    0,
    0,
    0,
    0,
    40,
    41,
    0,
    0,
    42,
    0,
    43,
    0,
    44,
    45,
    0,
    0,
    0,
    0,
    46,
    0,
    0,
    0,
    0,
    47,
    0,
    0,
    48,
    49,
    0,
    0,
    0,
    50,
    0,
    0,
    51,
    0,
    0,
    0,
    52,
    0,
    0,
    0,
    53,
    0,
    0,
    0,
    0,
    54,
    55,
    0,
    0,
    0,
    0,
    56,
    0,
    0,
    0,
    57,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    58,
    59,
    0,
    0,
    0,
    0,
    60,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    61,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  'hastitle': false,
  'jnotes': '<p>Jim here, sitting in for Jeff Chen, who is shredding a solo with his ax.</p>\r\n\r\n<p>Caleb Rasmussen had a <a href="https://www.xwordinfo.com/Crossword?date=10/25/2012">Tetris-themed crossword</a> a decade ago. Should Caleb sue Brandon? Should the famously litigious Tetris company sue the NYT? There are some interesting copyright issue parallels between Tetris and crossword puzzles.</p>\r\n\r\n<div><a href="https://en.wikipedia.org/wiki/Tetris"><img alt="" class="center" src="https://static1.makeuseofimages.com/wp-content/uploads/2014/07/tetris.jpg" style="width:700px" title="Caution: Falling Blocks" /></a></div>\r\n\r\n<p>You can&#39;t copyright &quot;ideas&quot; (like the rules of a game), but you can copyright expressions (implementations) of those ideas. That might seem clear, but it is open to vast interpretation that often has to be settled in court. <em>Tetris Holdings, LLC v. Xio Interactive, Inc.</em> confirmed that Tetris owned the shape of the pieces (called <em>tetrominoes</em> &mdash; that name now trademarked) and the exact 10x20 field size. If you make a Tetris clone, you will get sued. Even if the company doesn&#39;t consider you a threat, they have to take active steps to protect their claims, or they will lose them.</p>\r\n\r\n<p>Some games are copyrighted, and some aren&#39;t. The maker of Sudoku didn&#39;t protect his invention and never made a penny despite the huge popularity of that game. The KenKen inventor was more careful and presumably has made many pennies. Wordle had prior art and so isn&#39;t protected, but the NYT gave &quot;low seven figures&quot; to its inventor for the Wordle name and for the URL, which now redirects to nytimes.com.</p>\r\n\r\n<p>Crossword-like games were published as far back as the 1870s, and nobody claims they own that puzzle type, but crosswords uniquely contain themes and clues that are created anew for each puzzle. The NYT, like all publishers, claims copyright on each puzzle, and we dutifully include that mark on each we display, but it&#39;s not clear what exactly that protects. Themes, as we&#39;ve seen, repeat. There are only so many ways to clue words like ALAI. The complete grid and clue set seems like it deserves legal ownership, but what about <a href="https://slate.com/human-interest/2016/03/how-to-spot-a-plagiarized-crossword.html">grids that are so similar</a> they likely started from theft of another published puzzle? Or is that even theft?</p>\r\n\r\n<p>Without a definitive crossword case like <em>Tetris v Xio</em>, nobody knows where the boundaries are. Timothy Parker got defenestrated from <em>USA Today</em> and Universal Syndicate not through legal action but by public embarrassment. (NYT neither uncovered the plagiarism nor promoted the scandal.)</p>\r\n\r\n<p>I suspect publishers like it this way. If there ever were a court case that defined the rules &mdash; and copyright and patent case resolutions often seem random &mdash; then everyone would have to comply, even if the rules were stupid.</p>',
  'navigate': true,
  'publisher': 'The New York Times',
  'size': {
    'cols': 15,
    'rows': 19
  },
  'target': '/Crossword?date=9/9/2022',
  'title': '<span class=&#39;largeonly&#39;>New York Times, </span>Friday, September 9, 2022',
  'uniclue': false,
  'valid': true
}
